security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        my_mongo_provider:
            mongodb: {class: App\Document\DiscordUser, property: discordId}

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            # form_login:
            #     provider: fos_userbundle
            #     csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            guard:
                authenticators:
                    - App\Security\DiscordAuthenticator

    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/, role: ROLE_ADMIN }}
