stages:
- build
- update_google_mirror

build:
  variables:
    DOCKER_HOST: 'tcp://localhost:2375'
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - branches

upload:
  image: google/cloud-sdk
  stage: update_google_mirror
  script:
    - echo "$GITLAB_GOOGLE_SERVICE_ACCOUNT" > key.json && sleep 2 && gcloud auth activate-service-account --key-file key.json
    - gcloud builds submit --tag=gcr.io/zeue-net/tests/www-uag-zeue-net:latest
    - gsutil cp gs://zeue-net-secrets/app-engine-configs/www.uag.zeue.net/app.yaml .
    - gcloud app deploy ./app.yaml --image-url=gcr.io/zeue-net/tests/www-uag-zeue-net:latest --version=${CI_COMMIT_TAG//./-} --quiet
  only:
    - tags
