if: tag IS present
cache:
  directories:
  - $HOME/google-cloud-sdk
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update
- gcloud version
- openssl aes-256-cbc -K $encrypted_2062483a32c6_key -iv $encrypted_2062483a32c6_iv -in google_cred_zeue-net.json.enc -out google_cred_zeue-net.json -d
install: true
script:
- gcloud auth activate-service-account --key-file google_cred_zeue-net.json
- gcloud builds submit --tag=gcr.io/zeue-net/tests/www-uag-zeue-net:latest --project=zeue-net
- gsutil cp gs://zeue-net-secrets/app-engine-configs/www.uag.zeue.net/app.yaml .
- gcloud app deploy ./app.yaml --image-url=gcr.io/zeue-net/tests/www-uag-zeue-net:latest --version=${TRAVIS_TAG//./-} --quiet --project=zeue-net
