substitutions:
    _DEPLOYMENT_NAME: "www-unnamed-group"
    _GITHUB_REPO_SLUG: "uagpmc/www"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/${_GITHUB_REPO_SLUG}:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/github.com/${_GITHUB_REPO_SLUG}:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'env', 'deployment/${_DEPLOYMENT_NAME}', '--env', 'COMMIT_SHA=${COMMIT_SHA}', '--namespace', 'shared-webhost']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=regret'
