steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/zeue/run/$REPO_NAME:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/zeue/run/$REPO_NAME:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "$REPO_NAME",
        "--image=gcr.io/$PROJECT_ID/zeue/run/$REPO_NAME:latest",
        "--platform=managed",
        "--region=europe-west1",
        "--allow-unauthenticated",
        "--memory=128Mi",
        "--quiet",
      ]
