kind: pipeline
name: default

steps:
- name: google-cloudbuild
  image: google/cloud-sdk:latest # TODO: this is a big image, should be changed to `google/cloud-sdk:alpine` and initialise required components separately
  environment:
    KUBERNETES_DEPLOYMENT_NAME: loadouts-unnamed-group
    KUBERNETES_CLUSTER_NAME: cluster2-gcp-zeue-net
    KUBERNETES_CLUSTER_REGION: us-central1
    GOOGLE_PROJECT_NAME: zeue-personal
    TOKEN_B64:
      from_secret: google_keyfile
    CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  commands:
  - echo $TOKEN_B64 | base64 -d > /tmp/gcloud.json
  - gcloud auth activate-service-account --key-file "/tmp/gcloud.json"
  - gcloud builds submit --project=$GOOGLE_PROJECT_NAME
  - gcloud beta container clusters get-credentials $KUBERNETES_CLUSTER_NAME --region $KUBERNETES_CLUSTER_REGION --project $GOOGLE_PROJECT_NAME
  - kubectl patch deployment $KUBERNETES_DEPLOYMENT_NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
