substitutions:
    _DEPLOYMENT_NAME: "loadouts-unnamed-group"
    _GITHUB_REPO_SLUG: "uagpmc/loadouts"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/${_GITHUB_REPO_SLUG}:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/github.com/${_GITHUB_REPO_SLUG}:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'env', 'deployment/${_DEPLOYMENT_NAME}', '--env', 'COMMIT_SHA=${COMMIT_SHA}']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster2-gcp-zeue-net'
