name: Publish

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker login docker.pkg.github.com --username zeue --password ${{secrets.GITHUB_TOKEN}} && \
          docker build -t docker.pkg.github.com/$AUTHOR/$REPONAME/$REPONAME:latest . && \
          docker push docker.pkg.github.com/$AUTHOR/$REPONAME/$REPONAME:latest
        env:
          AUTHOR: zeue
          REPONAME: www-unnamed-group
